/**
 * Auth types — mirror of openapi/auth.yaml
 * N2 Daily Mock Exam webapp (Next.js App Router + Supabase)
 *
 * Goal.md OQ-3: magic link + persistent device sessions (long JWT TTL).
 * Covers: cp4 surface — subscriber logs in, takes mock, completes.
 *
 * Auto-generated by n2-build loop (wakeup 0070).
 * Source: openapi/auth.yaml (machine-readable auth contract).
 * Reversibility: rm lib/types/auth.ts — zero side-effects (no consumers yet).
 * Last synced: 2026-07-13 18:45 JST (n2-build wakeup 0090 — verify_types_openapi_sync.py flagged gap; fields verified in sync at 0090 run).
 */

// ---------------------------------------------------------------------------
// Schema: EmailAddress
// ---------------------------------------------------------------------------

/**
 * User email address. Validated client-side with the HTML5 `type="email"`
 * input constraint. Trimmed before being passed to `signInWithOtp`.
 *
 * @see openapi/auth.yaml › components.schemas.EmailAddress
 */
export type EmailAddress = string; // validated as email format by the HTML input

// ---------------------------------------------------------------------------
// Schema: SignInWithOtpRequest
// ---------------------------------------------------------------------------

/**
 * Parameters passed to `supabase.auth.signInWithOtp(...)` from the client at
 * `/auth` (`app/auth/page.tsx`). This is NOT a Next.js HTTP endpoint — it is
 * a direct call to the Supabase JS client's auth method, which internally
 * POSTs to `<supabase_url>/auth/v1/otp`.
 *
 * @see openapi/auth.yaml › components.schemas.SignInWithOtpRequest
 */
export interface SignInWithOtpRequest {
  email: EmailAddress;
  options?: {
    emailRedirectTo?: string; // Absolute URL; always `${origin}/auth/callback`
  };
}

// ---------------------------------------------------------------------------
// Schema: SignInWithOtpResponse
// ---------------------------------------------------------------------------

/**
 * Result of the `signInWithOtp` call.
 * On success (`error` is null), user is shown a "check your email" confirmation.
 * On failure, `error` contains a Supabase error code + message.
 *
 * @see openapi/auth.yaml › components.schemas.SignInWithOtpResponse
 */
export interface SignInWithOtpResponse {
  ok: boolean;
  error: null | {
    message: string;
    code: string;
  };
}

// ---------------------------------------------------------------------------
// Schema: SetSessionRequest
// ---------------------------------------------------------------------------

/**
 * Parameters passed to `supabase.auth.setSession(...)` from
 * `/auth/callback/route.ts`. The handler passes the magic-link token as BOTH
 * `access_token` and `refresh_token` (Supabase's magic-link flow packs both
 * into a single token).
 *
 * @see openapi/auth.yaml › components.schemas.SetSessionRequest
 */
export interface SetSessionRequest {
  access_token: string;
  refresh_token: string;
}

// ---------------------------------------------------------------------------
// Schema: SetSessionResponse
// ---------------------------------------------------------------------------

/**
 * Result of `setSession`. On success, the session cookie has been written and
 * the handler redirects to `next`. On failure, the handler redirects to
 * `/auth` with the error surfaced.
 *
 * @see openapi/auth.yaml › components.schemas.SetSessionResponse
 */
export interface SetSessionResponse {
  ok: boolean;
  error: null | {
    code: string;
    message: string;
  };
}

// ---------------------------------------------------------------------------
// Schema: AuthRedirectTarget
// ---------------------------------------------------------------------------

/**
 * The Location header value for the 302 redirect. Possible values:
 *   - `/today` — success (default `next`)
 *   - `/auth` — missing token or error
 *   - `/auth?error_code=...&error_description=...` — error variant (query-string appended by handler)
 *
 * @see openapi/auth.yaml › components.schemas.AuthRedirectTarget
 */
export type AuthRedirectTarget = '/today' | '/auth';

// ---------------------------------------------------------------------------
// Schema: SupabaseErrorCode
// ---------------------------------------------------------------------------

/**
 * Supabase auth error codes observed in the `/auth/callback` handler's
 * error-redirection path.
 *
 * @see openapi/auth.yaml › components.schemas.SupabaseErrorCode
 */
export type SupabaseErrorCode = 'unknown' | 'otp_expired' | 'access_denied';

// ---------------------------------------------------------------------------
// Type guards (discriminated-union narrowing)
// ---------------------------------------------------------------------------

/** Narrow `SignInWithOtpResponse` to its success variant */
export const isSignInSuccess = (r: SignInWithOtpResponse): r is SignInWithOtpResponse & { ok: true; error: null } =>
  r.ok === true && r.error === null;

/** Narrow `SignInWithOtpResponse` to its error variant */
export const isSignInError = (r: SignInWithOtpResponse): r is SignInWithOtpResponse & { ok: false; error: { message: string; code: string } } =>
  r.ok === false && r.error !== null;

/** Narrow `SetSessionResponse` to its success variant */
export const isSetSessionSuccess = (r: SetSessionResponse): r is SetSessionResponse & { ok: true; error: null } =>
  r.ok === true && r.error === null;

/** Narrow `SetSessionResponse` to its error variant */
export const isSetSessionError = (r: SetSessionResponse): r is SetSessionResponse & { ok: false; error: { code: string; message: string } } =>
  r.ok === false && r.error !== null;

/** Check whether a redirect target string is a success redirect */
export const isAuthSuccessRedirect = (target: string): target is '/today' =>
  target === '/today';

/** Check whether a redirect target string is an error redirect */
export const isAuthErrorRedirect = (target: string): target is '/auth' =>
  target === '/auth';
